### ISSUE TITLE
Licensing Page new Graph (Licensing as a Service)

### ISSUE THREAD

**Issue by anela-a** [SLASCONE/SLASCONE-demo-java#12]
licensing process graph by Dominic: [DB-Slascone-Grafik-20211022.pdf](https://github.com/SLASCONE/SLASCONE-demo-java/files/8480454/DB-Slascone-Grafik-20211022.pdf)
my suggestions: [licensing process graphs examples.pptx](https://github.com/SLASCONE/SLASCONE-demo-java/files/8480481/licensing.process.graphs.examples.pptx) @imichalarias

**Comment by imichalarias** [comment]
@anela-a: I uploaded the new graphic to https://slascone.com/licensing but it does look sharp, please talk with Benny about this, and we could/should also do some animation, as we do with the licensing/analytics cloud in the home page. Let us use this graphic for both EN and DE (we are not going to translate this graphic for now)

**Comment by imichalarias** [comment]
Reopened: Animation (website)
